### ISSUE TITLE
This vs `rake-js`

### ISSUE THREAD

**Issue by Berkmann18** [shopping24/rake-js#12]
I'm wondering how does this package differ to [`rake-js`](https://www.npmjs.com/package/rake-js) (other than being more recently updated)?
And why would one use this over `rake-js` or even [`rapid-automated-keyword-extraction`](https://www.npmjs.com/package/rapid-automated-keyword-extraction)?
I'm genuinely curious, as I'm unsure of what would suit my project needs.

**Comment by kitsunesensei** [comment]
Hi @Berkmann18, this project is a javascript version of the RAKE implementation provided by @zelandiya (https://github.com/zelandiya/RAKE-tutorial). Besides phrases divided by stopwords we return "adjoined keywords" that are combined by said stopwords (eg. Bike with Batman Sticker). Furthermore this library provides filtering options. Available options can be found at https://github.com/shopping24/rake-js/blob/develop/src/options.js.

We are investigating more methods and possibilities on filtering and sorting. The stable release refers to the ability set by the RAKE paper (https://www.researchgate.net/publication/227988510_Automatic_Keyword_Extraction_from_Individual_Documents). Depending on how far we come we may rename this project in the future.

**Comment by Berkmann18** [comment]
Ooh okay, thanks for the information.
