### ISSUE TITLE
Rake.js Playground Tests und Analyse

### ISSUE THREAD

**Issue by kayoken83** [shopping24/rake-js#5]
The playground should be tested in regards to feasibility and use. Useful configurations for different inputs should be checked.

**Comment by AlenaMuellerMoell** [comment]
https://docs.google.com/spreadsheets/d/1YmlSZ6eFS2SkX06rTivxtrwbNvXJQKI4F2RUw5Wzuzk/edit?folder=1WMu_dwDEWwbTFGVYoFtTm8cj3odfgoNr#gid=0
